### ISSUE TITLE
qrcodestandard

### ISSUE THREAD

**Issue by mic-rigaud** [GLMF/GLMF198#1]
Bonjour,
J'ai le magasine dans les mains, et je ne comprends pas où (ou comment) je peux trouver le fichier qrcodestandard.py
J'ai essaye de la reconstruire à partir du code donné dans l'article mais sans succès...
Merci de votre compréhension.

**Comment by tcolombo** [comment]
Bonjour,

Dans https://github.com/GLMF/GLMF194/tree/master/Reperes/QR_codes puisque plusieurs articles constituent la série.

**Comment by mic-rigaud** [comment]
Bonjour,
Merci et excusez moi pour le dérangement
Bonne journée
